### ISSUE TITLE
registerChatCommand() does not register command

### ISSUE THREAD

**Issue by TAXSET** [Vortexdata/tsq-plugin-framework#39]
**Bug Description**
Plugin commands registered via the registerChatCommand() method are not being registered and activated.

**To Reproduce**
1. Create a plugin that registers a chat command.
2. Connect to a Teamspeak server running the plugin.
3. Try to run the command.
4. The framework will return a "Command not found." response.

**Expected behavior**
Run the registerd command.

**Logs or Screenshots**
N/A

**Windows:**
 - Windows Version: 1809
 - Java Version: 11
 - Framework Version: 2.0.0 Mint preview

**Comment by VarChar42** [comment]
Fixed
